<!--h3>This new page is generated by CRM/Groupe/Page/MesGroupes.php</h3-->

{* Example: Display a variable directly *}
<!--p>The current time is {$currentTime}</p-->

{* Example: Display a translated string -- which happens to include a variable *}
<!--p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p-->

<ul>
{foreach from=$listeOfGroupe key=k item=v}
  <li><a href="detail-groupe?id={$v.id}">{$v.titre}</a></li>
      {foreachelse}
  <li>Aucun élément n'a été trouvé dans la recherche </li>
{/foreach}
</ul>
